name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Format code with Black
      run: black .

    - name: Lint code with Ruff
      run: ruff .

    - name: Run tests
      run: pytest

    - name: Build and Test Complete
      run: echo "Build and test completed successfully!"
